"""Tests for Lua script manager."""

import tempfile
from pathlib import Path

import pytest

from haproxy_translator.ir.nodes import ConfigIR, GlobalConfig, LuaScript
from haproxy_translator.lua.manager import LuaManager


class TestLuaManager:
    """Test Lua script management."""

    @pytest.fixture
    def temp_dir(self):
        """Create temporary directory for tests."""
        with tempfile.TemporaryDirectory() as tmpdir:
            yield Path(tmpdir)

    @pytest.fixture
    def manager(self, temp_dir):
        """Create Lua manager with temp directory."""
        return LuaManager(temp_dir)

    def test_manager_initialization(self, temp_dir):
        """Test manager initialization."""
        manager = LuaManager(temp_dir)
        assert manager.output_dir == temp_dir / "lua"
        assert manager.script_map == {}

    def test_extract_no_lua_scripts(self, manager):
        """Test extraction when no Lua scripts present."""
        ir = ConfigIR(name="test")
        result = manager.extract_lua_scripts(ir)
        assert result == ir

    def test_extract_inline_lua_script(self, manager):
        """Test extraction of inline Lua script."""
        lua_code = """
core.register_action("test_action", {"http-req"}, function(txn)
    txn:set_var("req.test", "value")
    return core.DONE
end)
"""
        ir = ConfigIR(
            name="test",
            global_config=GlobalConfig(
                lua_scripts=[
                    LuaScript(
                        name="test_script",
                        source_type="inline",
                        content=lua_code,
                    )
                ]
            ),
        )

        result = manager.extract_lua_scripts(ir)

        # Should create lua directory
        assert manager.output_dir.exists()

        # Should have one script in map
        assert len(manager.script_map) == 1
        assert "test_script" in manager.script_map

        # File should exist
        lua_file = manager.script_map["test_script"]
        assert lua_file.exists()
        assert lua_file.suffix == ".lua"

        # File should contain the code with header
        content = lua_file.read_text()
        assert "Generated Lua script: test_script" in content
        assert "Auto-generated by HAProxy Config Translator" in content
        assert lua_code.strip() in content

        # IR should be updated
        assert result.global_config is not None
        updated_script = result.global_config.lua_scripts[0]
        assert updated_script.source_type == "file"
        assert updated_script.content == str(lua_file)

    def test_extract_unnamed_lua_script(self, manager):
        """Test extraction of unnamed Lua script generates hash-based name."""
        lua_code = "core.log(core.info, 'test')"
        ir = ConfigIR(
            name="test",
            global_config=GlobalConfig(
                lua_scripts=[
                    LuaScript(
                        source_type="inline",
                        content=lua_code,
                    )
                ]
            ),
        )

        manager.extract_lua_scripts(ir)

        # Should generate hash-based filename
        assert len(manager.script_map) == 1
        assert "unnamed" in manager.script_map
        lua_file = manager.script_map["unnamed"]
        assert lua_file.name.startswith("generated_")
        assert lua_file.suffix == ".lua"

    def test_keep_file_reference_scripts(self, manager):
        """Test that file reference scripts are kept as-is."""
        ir = ConfigIR(
            name="test",
            global_config=GlobalConfig(
                lua_scripts=[
                    LuaScript(
                        name="external",
                        source_type="file",
                        content="/etc/haproxy/scripts/auth.lua",
                    )
                ]
            ),
        )

        result = manager.extract_lua_scripts(ir)

        # Should keep the file reference
        updated_script = result.global_config.lua_scripts[0]
        assert updated_script.source_type == "file"
        assert updated_script.content == "/etc/haproxy/scripts/auth.lua"

        # Should add to script map
        assert "external" in manager.script_map
        assert manager.script_map["external"] == Path("/etc/haproxy/scripts/auth.lua")

    def test_interpolate_lua_template(self, manager):
        """Test interpolation of template parameters in Lua code."""
        lua_code = """
core.register_action("rate_limit", {"http-req"}, function(txn)
    local max_rate = ${max_requests}
    local period = ${time_period}
    -- rate limiting logic
end)
"""
        ir = ConfigIR(
            name="test",
            global_config=GlobalConfig(
                lua_scripts=[
                    LuaScript(
                        name="rate_limiter",
                        source_type="inline",
                        content=lua_code,
                        parameters={"max_requests": 100, "time_period": 60},
                    )
                ]
            ),
        )

        manager.extract_lua_scripts(ir)

        # Read generated file
        lua_file = manager.script_map["rate_limiter"]
        content = lua_file.read_text()

        # Should have interpolated values
        assert "${max_requests}" not in content
        assert "${time_period}" not in content
        assert "local max_rate = 100" in content
        assert "local period = 60" in content

    def test_sanitize_filename(self, manager):
        """Test filename sanitization."""
        assert manager._sanitize_filename("test_script") == "test_script"
        assert manager._sanitize_filename("Test-Script") == "test_script"
        assert manager._sanitize_filename("test.script!@#") == "test_script___"
        assert manager._sanitize_filename("my-auth-checker") == "my_auth_checker"

    def test_multiple_lua_scripts(self, manager):
        """Test extraction of multiple Lua scripts."""
        ir = ConfigIR(
            name="test",
            global_config=GlobalConfig(
                lua_scripts=[
                    LuaScript(
                        name="script1",
                        source_type="inline",
                        content="core.log(core.info, 'script1')",
                    ),
                    LuaScript(
                        name="script2",
                        source_type="inline",
                        content="core.log(core.info, 'script2')",
                    ),
                    LuaScript(
                        name="external",
                        source_type="file",
                        content="/etc/lua/external.lua",
                    ),
                ]
            ),
        )

        manager.extract_lua_scripts(ir)

        # Should have 3 scripts in map
        assert len(manager.script_map) == 3
        assert "script1" in manager.script_map
        assert "script2" in manager.script_map
        assert "external" in manager.script_map

        # Inline scripts should have generated files
        assert manager.script_map["script1"].exists()
        assert manager.script_map["script2"].exists()

    def test_get_lua_load_directives(self, manager):
        """Test getting lua-load directives."""
        ir = ConfigIR(
            name="test",
            global_config=GlobalConfig(
                lua_scripts=[
                    LuaScript(
                        name="script1",
                        source_type="inline",
                        content="-- script 1",
                    ),
                    LuaScript(
                        name="script2",
                        source_type="file",
                        content="/etc/lua/script2.lua",
                    ),
                ]
            ),
        )

        manager.extract_lua_scripts(ir)
        directives = manager.get_lua_load_directives()

        # Should have 2 directives
        assert len(directives) == 2
        assert all(d.startswith("lua-load") for d in directives)

    def test_get_script_paths(self, manager):
        """Test getting script path map."""
        ir = ConfigIR(
            name="test",
            global_config=GlobalConfig(
                lua_scripts=[
                    LuaScript(
                        name="test",
                        source_type="inline",
                        content="-- test",
                    )
                ]
            ),
        )

        manager.extract_lua_scripts(ir)
        paths = manager.get_script_paths()

        # Should return copy of script map
        assert len(paths) == 1
        assert "test" in paths
        assert isinstance(paths["test"], Path)

    def test_lua_directory_creation(self, manager, temp_dir):
        """Test that lua directory is created on first extract."""
        lua_dir = temp_dir / "lua"
        assert not lua_dir.exists()

        ir = ConfigIR(
            name="test",
            global_config=GlobalConfig(
                lua_scripts=[
                    LuaScript(
                        name="test",
                        source_type="inline",
                        content="-- test",
                    )
                ]
            ),
        )

        manager.extract_lua_scripts(ir)

        # Directory should now exist
        assert lua_dir.exists()
        assert lua_dir.is_dir()


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
