"""Lua script extraction and management."""

from pathlib import Path
from typing import Optional
import hashlib
import dataclasses

from ..ir.nodes import ConfigIR, GlobalConfig, LuaScript
from ..utils.errors import CodeGenerationError


class LuaManager:
    """Manage Lua script extraction and generation."""

    def __init__(self, output_dir: Path):
        self.output_dir = Path(output_dir) / "lua"
        self.script_map: dict[str, Path] = {}

    def extract_lua_scripts(self, ir: ConfigIR) -> ConfigIR:
        """
        Extract inline Lua to files and update IR with references.

        Args:
            ir: Configuration IR

        Returns:
            Updated IR with file references instead of inline scripts
        """
        if not ir.global_config or not ir.global_config.lua_scripts:
            return ir

        # Create output directory
        self.output_dir.mkdir(parents=True, exist_ok=True)

        updated_scripts = []

        for script in ir.global_config.lua_scripts:
            if script.source_type == "inline":
                # Generate file for inline script
                filepath = self._generate_lua_file(script)
                self.script_map[script.name or "unnamed"] = filepath

                # Create new script pointing to file
                updated_script = dataclasses.replace(
                    script, source_type="file", content=str(filepath)
                )
                updated_scripts.append(updated_script)
            else:
                # Keep file references as-is
                updated_scripts.append(script)
                if script.content:
                    self.script_map[script.name or "unnamed"] = Path(script.content)

        # Update global config with new scripts
        updated_global = dataclasses.replace(
            ir.global_config, lua_scripts=updated_scripts
        )

        return dataclasses.replace(ir, global_config=updated_global)

    def _generate_lua_file(self, script: LuaScript) -> Path:
        """Generate Lua file from inline script."""
        # Create filename from script name or hash
        if script.name:
            filename = self._sanitize_filename(script.name) + ".lua"
        else:
            hash_val = hashlib.sha256(script.content.encode()).hexdigest()[:8]
            filename = f"generated_{hash_val}.lua"

        filepath = self.output_dir / filename

        # Interpolate template variables if present
        content = self._interpolate_lua_template(script)

        # Add header comment
        header = f"-- Generated Lua script: {script.name or 'unnamed'}\n"
        header += "-- Auto-generated by HAProxy Config Translator\n\n"

        # Write Lua file
        filepath.write_text(header + content, encoding="utf-8")

        return filepath

    def _interpolate_lua_template(self, script: LuaScript) -> str:
        """Interpolate ${param} in Lua code."""
        content = script.content

        for param_name, param_value in script.parameters.items():
            placeholder = f"${{{param_name}}}"
            content = content.replace(placeholder, str(param_value))

        return content

    def _sanitize_filename(self, name: str) -> str:
        """Sanitize name for use as filename."""
        # Replace non-alphanumeric characters with underscores
        import re

        sanitized = re.sub(r"[^a-zA-Z0-9_]", "_", name)
        return sanitized.lower()

    def get_lua_load_directives(self) -> list[str]:
        """Get list of lua-load directives for generated config."""
        return [f"lua-load {path}" for path in self.script_map.values()]

    def get_script_paths(self) -> dict[str, Path]:
        """Get map of script names to file paths."""
        return dict(self.script_map)
